services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Posts\Conditional\Users\Hooks\:
        resource: '../../../src/Conditional/Users/Hooks/*'
        public: true
