services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Posts\Conditional\Taxonomies\Hooks\:
        resource: '../../../src/Conditional/Taxonomies/Hooks/*'
        public: true
