services:
    PoP\Posts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Posts\TypeResolverPickers\:
        resource: '../src/TypeResolverPickers/*'
        public: true

    PoP\Posts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
