services:
    PoP\Posts\Conditional\API\RouteModuleProcessors\:
        resource: '../src/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\Posts\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../src/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true

    PoP\Posts\FieldValueResolvers\:
        resource: '../src/FieldValueResolvers/*'
        public: true
